
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 13 20:34:48 GMT 2014
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface QSym {
  /* terminals */
  public static final int GREATERTHAN = 47;
  public static final int CHARLITERAL = 27;
  public static final int LEFTBRACKET = 8;
  public static final int DIVIDE = 40;
  public static final int GREATERTHANEQUAL = 48;
  public static final int POWER = 41;
  public static final int LEFTTBRACKET = 10;
  public static final int CHAR = 19;
  public static final int CONCAT = 44;
  public static final int TUPLE = 20;
  public static final int RIGHTPAREN = 13;
  public static final int RIGHTBRACKET = 9;
  public static final int NOTEQUAL = 50;
  public static final int REPEAT = 53;
  public static final int INT = 15;
  public static final int MINUS = 38;
  public static final int RIGHTTBRACKET = 11;
  public static final int LEFTPAREN = 12;
  public static final int FLOATLITERAL = 25;
  public static final int LESSTHANEQUAL = 46;
  public static final int AND = 36;
  public static final int NOT = 34;
  public static final int SEMICOLON = 2;
  public static final int LESSTHAN = 45;
  public static final int IN = 42;
  public static final int OR = 35;
  public static final int TDEF = 29;
  public static final int BOOL = 14;
  public static final int COMMA = 3;
  public static final int UNTIL = 54;
  public static final int MULTIPLY = 39;
  public static final int PLUS = 37;
  public static final int IF = 51;
  public static final int ASSIGN = 33;
  public static final int DOT = 4;
  public static final int ID = 22;
  public static final int EOF = 0;
  public static final int RETURN = 55;
  public static final int EQUAL = 49;
  public static final int error = 1;
  public static final int BOOLLITERAL = 23;
  public static final int FDEF = 28;
  public static final int VOID = 21;
  public static final int INTLITERAL = 24;
  public static final int FOREACH = 58;
  public static final int RIGHTBRACE = 7;
  public static final int COLON = 5;
  public static final int ELSE = 52;
  public static final int DICT = 30;
  public static final int READ = 31;
  public static final int WHILE = 57;
  public static final int LIST = 18;
  public static final int LEFTBRACE = 6;
  public static final int FLOAT = 16;
  public static final int STRING = 17;
  public static final int STRINGLITERAL = 26;
  public static final int DO = 56;
  public static final int LENGTH = 43;
  public static final int PRINT = 32;
}

